["Common configs for JITL"]
	#Need structure to use Summoning Table
	"Summoning structure: " = true
	#Can Mobs drop Loot Pouches
	"Loot Pouches: " = true
	#Common Loot Chance
	"Common Loot Chance 1 out of: " = 100
	#Gold Loot Chance
	"Gold Loot Chance 1 out of: " = 150
	#Diamond Loot Chance
	"Diamond Loot Chance 1 out of: " = 200
	#how far to look for portal locations.
	# Default: 24
	# Range: 1 ~ 128
	"Portal Search Radius" = 24
	#Can use Eternal Light to change time to night
	"Value: " = true
