# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				dolphin = true
				pufferfish = true
				item = true
				axolotl = true
				zombie_villager = true
				tropical_fish = true
				pillager = true
				skeleton = true
				iron_golem = true
				bat = true
				rabbit = true
				zombie = true
				glow_squid = true
				cod = true
				witch = true
				glow_item_frame = false
				squid = true
				drowned = true
				spider = true
				creeper = true
				player = true
				enderman = true

			[light_sources.settings.entities.naturalist]
				rattlesnake = true
				tortoise = true
				coral_snake = true
				lizard = true

			[light_sources.settings.entities.endermanoverhaul]
				cave_enderman = true
				ocean_enderman = true

			[light_sources.settings.entities.rottencreatures]
				undead_miner = true

			[light_sources.settings.entities.resourcechickens]
				sand = true
				chicken = true
				duck = true
				flint = true
				cacti = true

			[light_sources.settings.entities.creeperoverhaul]
				ocean_creeper = true
				dripstone_creeper = true
				cave_creeper = true

			[light_sources.settings.entities.hookshot]
				hookshot = true

